context:
  name: pydiverse-pipedag
  version: "0.9.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pydiverse_pipedag-${{ version }}.tar.gz
  sha256: 79065ad7f69d1523a6f5048abbae1ccf0df2917fe04bbfc151d4ff4736c2a313

build:
  noarch: python
  script: python -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - typing_extensions >=4.1.0
    - pyparsing >=3.0
    - click >=8.1.3
    - pydot >=1.4.2
    - python >=${{ python_min }}
    - pandas >=1.4.3
    - sqlalchemy >=1.4.39
    - typing-extensions >=4.1.0
    - networkx >=2.8
    - attrs >=22.1.0
    - structlog >=22.1.0
    - pynng >=0.7.1
    - msgpack-python >=1.0.4
    - packaging >=21.3
    - python-box >=6.1.0
    - pyyaml >=6.0
    - pyarrow >=11.0.0
    - cryptography >=41.0.1

tests:
  - python:
      imports:
        - pydiverse.pipedag
      pip_check: true
      python_version: ${{ python_min }}

about:
  homepage: https://github.com/pydiverse/pydiverse.transform
  documentation: https://pydiversetransform.readthedocs.io
  summary: Pipe based dataframe manipulation library that can also transform data on SQL databases
  description: A pipeline orchestration library executing tasks within one python session. It takes care of SQL table (de)materialization, caching and cache invalidation. Blob storage is supported as well for example for storing model files.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - finn-rudolph
    - pavelzw
    - NMAC427
    - windiana42
